# Generated by Django 5.0.6 on 2026-04-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_horario_y_sin_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nota_admin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='sitio_web',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='sin_horario',
            field=models.BooleanField(default=False, help_text='Marcar si el recurso no tiene horario fijo (disponible siempre o variable)'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='sin_stock_fecha',
            field=models.DateField(blank=True, help_text='Fecha en que se activó sin_stock (para auto-resetear al día siguiente)', null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='sin_stock_hoy',
            field=models.BooleanField(default=False, help_text='La organización lo activa cuando se quedaron sin stock antes del horario'),
        ),
    ]
