# Generated by Django 5.0.6 on 2026-04-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_alter_organizacion_descripcion_alter_organizacion_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo')], max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_revision', 'En revisión'), ('resuelto', 'Resuelto')], default='nuevo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'PQR',
                'ordering': ['-creado_en'],
            },
        ),
    ]
